name: "fraud-detection"
platform: "onnxruntime_onnx"
max_batch_size: 0

input [
    {
        name: "input"
        data_type: TYPE_FP32
        dims: [1,20]
    }
]

output [
    {
        name: "probabilities"
        data_type: TYPE_FP32
        dims: [1, 2]
    }
]

