name: "geolocation-fraud-detection"
platform: "xgboost"
max_batch_size: 0

input [
    {
        name: "input__0"
        data_type: TYPE_FP32
        dims: [20]
    }
]

output [
    {
        name: "probabilities"
        data_type: TYPE_FP32
        dims: [2]
    }
]

